sudo: required
dist: xenial
language: go
go:
  - "1.14.x"

matrix:
  include:
    - os: linux
      env: VERSION_UPGRADE_TEST_WAIT_TIMEOUT=45s
    - os: osx
      # Do not start osx build for PR
      if: type != pull_request
      osx_image: xcode8
      env: VERSION_UPGRADE_TEST_WAIT_TIMEOUT=60s

script:
  - make install
